services:
  redis:
    image: redis
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - '5540:5540'

  app:
    build:
      target: production
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - JwtSettings__Secret=${JwtSettings__Secret:?}
      - JwtSettings__ExpiryMinutes=${JwtSettings__ExpiryMinutes:?}
      - JwtSettings__Issuer=${JwtSettings__Issuer:?}
      - JwtSettings__Audience=${JwtSettings__Audience:?}

      - FileStorageSettings__AccessKey=${FileStorageSettings__AccessKey:?}
      - FileStorageSettings__SecretKey=${FileStorageSettings__SecretKey:?}
      - FileStorageSettings__BucketName=${FileStorageSettings__BucketName:?}
      - FileStorageSettings__EndpointUrl=${FileStorageSettings__EndpointUrl:?}
      - FileStorageSettings__BucketUrl=${FileStorageSettings__BucketUrl:?}

      - RedisSettings__ConnectionString=${RedisSettings__ConnectionString:-redis:6379}

      - PostgresSettings__ConnectionString=${PostgresSettings__ConnectionString:?}

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?}
      - POSTGRES_USER=${POSTGRES_USER:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
